# Generated by Django 4.0.3 on 2022-03-29 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('calorie', models.FloatField(default=0, null=True)),
                ('glucidi', models.FloatField(default=0, null=True)),
                ('proteine', models.FloatField(default=0, null=True)),
                ('lipidi', models.FloatField(default=0, null=True)),
                ('amido', models.FloatField(default=0, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='food.category')),
            ],
            options={
                'verbose_name_plural': 'ingredients',
            },
        ),
    ]
